# Generated by Django 5.1.5 on 2025-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests_sent',
            field=models.ManyToManyField(related_name='friend_requests_received', to='login.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='login.user'),
        ),
    ]
