# Generated by Django 5.1.6 on 2025-02-05 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting to Start Match'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pong Match',
                'verbose_name_plural': 'Pong Matches',
            },
        ),
    ]
