# Generated by Django 5.1.6 on 2025-03-02 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_pongtournament_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PongMatch',
            new_name='PongGameModel',
        ),
        migrations.RenameModel(
            old_name='PongTournament',
            new_name='PongTournamentModel',
        ),
    ]
