# Generated by Django 5.1.7 on 2025-03-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_rename_pongmatch_ponggamemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongtournamentmodel',
            name='lobby_id',
            field=models.CharField(default='missing', max_length=100),
        ),
        migrations.AddField(
            model_name='pongtournamentmodel',
            name='size',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
