# Generated by Django 5.1.7 on 2025-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_pongtournamentmodel_lobby_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongtournamentmodel',
            name='leaderboard',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
