FROM nginx:alpine

RUN apk add openssl

RUN mkdir -p /etc/nginx/ssl
# orignal 2048
RUN openssl req -x509 -nodes -days 100 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx-selfsigned.key \
	-out /etc/nginx/ssl/nginx-selfsigned.crt -subj "/C=DE/O=42/OU=student/CN=transcendence.de"

COPY ./default.conf /etc/nginx/conf.d/default.conf

# RUN chmod 755 /var/www/transcendence
# RUN chown -R www-data:www-data /var/www/transcendence

# COPY ./../../../frontend /var/www/transcendence

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
