# Generated by Django 5.1.5 on 2025-01-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_friend_requests_sent_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend_requests_received', to='login.user'),
        ),
    ]
