FROM python:3.13-slim

WORKDIR /app

COPY . /app/

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*


RUN chmod +x /app/start_server.sh &&\
	pip install --no-cache-dir -r requirements.txt

CMD ["/app/start_server.sh"]
