# Generated by Django 5.1.6 on 2025-02-05 21:07

import player.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=player.models.get_profile_picture_upload_path),
        ),
    ]
